/* Automatically generated by './build/bin/build-entry.js' */

import TestComp from '../packages/test-comp/index.js';
import Scrollbar from '../packages/scrollbar/index.js';
import TreeSelect from '../packages/tree-select/index.js';

const components = [
	TestComp,
	Scrollbar,
	TreeSelect];

const install = function(Vue, opts = {}) {

	components.forEach(component => {
		Vue.component(component.name, component);
	});

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
	install(window.Vue);
}

export default {
	version: '0.0.1',
	install,
	TestComp,
	Scrollbar,
	TreeSelect
};
